// const searchList = [
//   "L'Oréal Paris Powder Foundation, Super-Blendable, With Hyaluronic Acid, Light Texture for a Flawless Finish, True Match Perfecting Powder, N4",
//   "Maybelline Superstay 24 Hour Lipstick, Soft Taupe, 9 ml",
//   "Maybelline New York Tattoo Brow Peel Off Eyebrow Gel Tint, Semi-Permanent Colour, Waterproof, Lasts up to 3 Days, Colour: Black Brown",
//   "L'Oréal Paris Liquid Foundation, Full Coverage, Lasting Wear, With Vitamin C and SPF 25, Infallible 32H Fresh Wear, 60 Rose Ivory",
//   "Maybelline New York Lash Sensational Sky High Mascara, Volumising & Lengthening Mascara, Washable Flake-Free Formula Infused With Bamboo Extract & Fib",
//   "L'Oréal Paris Powder Foundation, Super-Blendable, With Hyaluronic Acid, Light Texture for a Flawless Finish, True Match Perfecting Powder, C2",
//   "e.l.f. Halo Glow Contour Beauty Wand, Liquid Contour Wand For A Naturally Sculpted Look, Buildable Formula, Vegan & Cruelty-free, Medium/Tan",
//   "e.l.f. Halo Glow Contour Beauty Wand, Liquid Contour Wand For A Naturally Sculpted Look, Buildable Formula, Vegan & Cruelty-free, Tan/Deep",
//   "e.l.f. Halo Glow Blush Beauty Wand, Liquid Blush Wand For Radiant, Flushed Cheeks, Infused With Squalane, Vegan & Cruelty-free, Berry Radiant",
//   "e.l.f. Halo Glow Contour Beauty Wand, Liquid Contour Wand For A Naturally Sculpted Look, Buildable Formula, Vegan & Cruelty-free, Light/Medium",
//   "e.l.f. Halo Glow Highlight Beauty Wand, Liquid Highlighter Wand For Luminous, Glowing Skin, Buildable Formula, Vegan & Cruelty-free, Champagne Campaig",
//   "e.l.f. O Face Satin Lipstick, Richly Pigmented, Nourishing & Long-Lasting Creamy Lipstick, Infused With Jojoba, Vegan & Cruelty-Free, Standing Ovation",
//   "Bio-Kult Everyday Multi-Strain Formulation Probiotics for Digestive System, 60 Capsules (Pack of 1)",
//   "L'Oreal Paris Volume Million Lashes Mascara Black Waterproof, Gives Lashes Intense, Defined Volume with No Clumps"
// ];

// let searchList = [];
// let searchList = ["Maybelline"]
// let searchList = ["Supplements (Health & Household"]

const searchList = [
  "Moisturizer",
  "Serum",
  "Face mask",
  "Sunscreen",
  "Eye cream",
  "Lip balm",
  "Acne treatment",
  "Anti-aging cream",
  "Hair, Skin, and Nails supplement",
  "Vitamin C supplement",
  "Vitamin D supplement",
  "Fish oil supplement",
  "Probiotic supplement",
  "Collagen supplement",
  "Multivitamin supplement",
  "Weight loss supplement",
  "Protein powder",
  "Pre-workout supplement",
  "Post-workout supplement",
  "Hair growth supplement",
  "Hair removal cream",
  "Shampoo",
  "Conditioner",
  "Hair mask",
  "Hair serum",
  "Dry shampoo",
  "Face primer",
  "Setting spray",
  "Makeup sponge",
  "Makeup bag",
  "False eyelashes",
  "Nail polish",
  "Makeup mirror",
  "Facial scrub",
  "Body lotion",
  "Body wash",
  "Deodorant",
  "Perfume",
  "Cologne",
  "Facial roller",
  "Body oil",
  "Hand cream",
  "Foot cream",
  "Bath salts",
  "Sheet mask",
  "Body scrub",
  "Foot scrub",
  "Cuticle oil",
  "Tinted moisturizer",
  "BB cream",
  "CC cream",
  "Primer",
  "Makeup setting powder",
  "Makeup setting spray",
  "Makeup setting mist",
  "Micellar water",
  "Eyebrow gel",
  "Eyelash curler",
  "Makeup palette",
  "Makeup organizer",
  "Makeup case",
  "Compact mirror",
  "Makeup brush cleaner",
  "Hairbrush",
  "Comb",
  "Hair accessories",
  "Hair ties",
  "Hair clips",
  "Hair bands",
  "Hairpins",
  "Hair extensions",
  "Hair dye",
  "Hair bleach",
  "Hair treatment oil",
  "Hair mask",
  "Hair styling gel",
  "Hair styling cream",
  "Hair styling mousse",
  "Hair styling wax",
  "Hair volumizer",
  "Hair texturizer",
  "Hair shine spray",
  "Hair heat protectant",
  "Hair serum",
  "Hair straightener",
  "Hair curling iron",
  "Hair dryer",
];

module.exports = { searchList };
